### ISSUE TITLE
Support for multiple controllers

### ISSUE THREAD

**Issue by bosserman** [mendhak/xbox-controller-off#3]
Could someone edit this to allow the script to turn off up to 4 controllers? As it stands only the first controller will be affected. I don't have the scripting skill necessary to figure it out myself.

**Comment by Catarax** [comment]
Tested, shutdown the 4 wireless controller.

Should really be added in the main branch.

**Comment by mendhak** [comment]
OK - merged the branch.  I'm on Linux these days so unable to compile the .exe.  Then again, that might not be a bad thing
